{
 "title": "Directory Quotas",
 "description": "View Directy Quotas",
 "tags": [ "isilon" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "path",
    "label": "Path",
    "query": "show tag values with key =\"path\""
   }
  ]
 },
 "panels": [
  {
   "title": "Advisory Quotas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "phys",
     "measurement": "quota",
     "query": "SELECT \"quotaid\", \"phys\" FROM \"quota\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"path\" =~ /^$path$/ AND \"quotatype\" = 'directory') AND $timeFilter",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "phys" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "quotatype", "operator": "=", "value": "directory" }
     ]
    },
    {
     "alias": "advisory",
     "measurement": "quota",
     "query": "SELECT \"quotaid\", \"phys\" FROM \"quota\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"path\" =~ /^$path$/ AND \"quotatype\" = 'directory') AND $timeFilter",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "advise" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "quotatype", "operator": "=", "value": "directory" }
     ]
    }
   ]
  },
  {
   "title": "Hard Quotas",
   "type": "graph",
   "description": "Display the hard quotas set on the path.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Hard",
     "measurement": "quota",
     "query": "SELECT \"quotaid\", \"hard\" FROM \"quota\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"path\" =~ /^$path$/ AND \"quotatype\" = 'directory') AND $timeFilter",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "hard" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "quotatype", "operator": "=", "value": "directory" }
     ]
    },
    {
     "alias": "Physical",
     "measurement": "quota",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "phys" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "quotatype", "operator": "=", "value": "directory" }
     ]
    },
    {
     "alias": "Soft",
     "measurement": "quota",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "soft" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "quotatype", "operator": "=", "value": "directory" }
     ]
    }
   ]
  },
  {
   "title": "Logical Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "measurement": "quota",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "phys" ], "type": "field" }
      ],
      [
       { "params": [ "applog" ], "type": "field" }
      ],
      [
       { "params": [ "fslog" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "quotatype", "operator": "=", "value": "directory" }
     ]
    }
   ]
  }
 ]
}