{
 "title": "Quota reports",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "qtype",
    "label": "Quota Type",
    "query": "\tshow tag values with key = \"quotatype\""
   },
   {
    "name": "path",
    "label": "Path",
    "query": "\tshow tag values with key = \"path\" where quotatype =~/^$qtype/"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of reports available",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "quota",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "quotatype", "operator": "=~", "value": "/^$qtype$/" }
     ]
    }
   ]
  },
  {
   "title": "Quota Reports Available",
   "type": "table",
   "description": "Contains a list of the quota reports available on Isilon",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "measurement": "report",
     "query": "SELECT * FROM \"report\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"type\" =~ /^$detail$/) and $timeFilter\n",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Quota Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "quotatype" ], "type": "tag" }
     ],
     "measurement": "quota",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "hard" ], "type": "field" }
      ],
      [
       { "params": [ "soft" ], "type": "field" }
      ],
      [
       { "params": [ "advise" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" }
     ]
    }
   ]
  },
  {
   "title": "Hard Quotas",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "measurement": "quota",
     "query": "SELECT \"value\", \"fslog\" FROM \"quota\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"path\" =~ /^$path$/) AND $timeFilter GROUP BY \"persona\"",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "phys" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "hard", "operator": "!=", "value": "null" }
     ]
    },
    {
     "alias": "hard",
     "measurement": "quota",
     "query": "SELECT \"value\", \"fslog\" FROM \"quota\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"path\" =~ /^$path$/) AND $timeFilter GROUP BY \"persona\"",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "hard" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "hard", "operator": "!=", "value": "null" }
     ]
    }
   ]
  }
 ]
}