{
 "title": "User Quotas",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values with key = \"cluster\""
   },
   {
    "name": "path",
    "label": "Path",
    "query": "show tag values with key=\"path\" where quotatype=~/user/"
   },
   {
    "name": "persona",
    "label": "User ID",
    "query": "show tag values with  key=\"persona\" where path=~/$path/"
   }
  ]
 },
 "panels": [
  {
   "title": "Hard Quota",
   "type": "stat",
   "description": "Users Hard Quota",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"quotaid\",\"hard\" from quota where (path =~/$path$/  AND persona =~ /$persona$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soft Quota",
   "type": "stat",
   "description": "Users Soft Quota",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"quotaid\",\"soft\" from quota where (path =~/$path$/  AND persona =~ /$persona$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Advisory Quota",
   "type": "stat",
   "description": "Users Advisory Quota",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"quotaid\",\"advise\" from quota where (path =~/$path$/  AND persona =~ /$persona$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Physical usage",
   "type": "graph",
   "description": "just the physical used during the time range",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Physical $tag_persona",
     "groupBy": [
      { "params": [ "persona" ], "type": "tag" }
     ],
     "measurement": "quota",
     "query": "SELECT \"quotaid\", \"phys\" FROM \"quota\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"path\" =~ /^$path$/ AND \"persona\" =~ /^$persona$/) AND $timeFilter GROUP BY \"persona\"",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "advise" ], "type": "field" }
      ],
      [
       { "params": [ "hard" ], "type": "field" }
      ],
      [
       { "params": [ "soft" ], "type": "field" }
      ],
      [
       { "params": [ "phys" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "persona", "operator": "=~", "value": "/^$persona$/" }
     ]
    }
   ]
  },
  {
   "title": "User Quota",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "phys",
     "groupBy": [
      { "params": [ "persona" ], "type": "tag" }
     ],
     "measurement": "quota",
     "query": "SELECT \"quotaid\", \"phys\" FROM \"quota\" WHERE (\"cluster\" =~ /^$cluster$/ AND \"path\" =~ /^$path$/)",
     "select": [
      [
       { "params": [ "quotaid" ], "type": "field" }
      ],
      [
       { "params": [ "phys" ], "type": "field" }
      ],
      [
       { "params": [ "fslog" ], "type": "field" }
      ],
      [
       { "params": [ "applog" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$path$/" },
      { "condition": "AND", "key": "persona", "operator": "=~", "value": "/^$persona$/" }
     ]
    }
   ]
  }
 ]
}